In [21]:
#Miral Panchal - 100569725
import numpy as np
import random as rnd

def WhiteWash(array):
    #Color map for white
    white = np.array([[1,1,1]])
    #Adds white to color
    array[:][:] = (np.add(array[:][:] , white)/2)
        
    return array

#Makes array of 0s with dimensions mx3, where m = 5
m = 5
array = np.zeros((m, 3))    

#Fills each cell with a random float from 0 to 1
for i in range (0,m):
    for j in range (0,3):
        array[i][j] = rnd.uniform(0,1)

#Prints the array before adding white
print(array,'\n')
#Calls the WhiteWash function and passes the array in it
new_array = WhiteWash (array)
#Prints the array after adding white
print (new_array)

[[ 0.52224413  0.90072204  0.54511785]
 [ 0.34698456  0.16083459  0.07202283]
 [ 0.3428056   0.26099041  0.74686734]
 [ 0.09701258  0.38680411  0.31140192]
 [ 0.82657167  0.4576478   0.91498538]] 

[[ 0.76112206  0.95036102  0.77255892]
 [ 0.67349228  0.58041729  0.53601141]
 [ 0.6714028   0.63049521  0.87343367]
 [ 0.54850629  0.69340206  0.65570096]
 [ 0.91328584  0.7288239   0.95749269]]
